name: Forge Sizes Check

on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  check:
    name: Sizes Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Apply patch
        run: |
          cd lib/example-native-token-transfers
          git apply ../../.github/example-native-token-transfers.diff

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: |
          forge --version
          make sizes
        id: build
